version: '3.8'

services:
  app:
    container_name: wwebjs_api
    image: avoylenko/wwebjs-api:latest
    restart: always
    ports:
      - "3000"
    environment:
      - BASE_WEBHOOK_URL=https://whatsapp-server.apps.pundidigitaldynamics.net/api/v1/webhook/wwebjs
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=FALSE
      - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE
      - CHROME_BIN=/usr/bin/chromium
    volumes:
      - wwebjs_sessions:/usr/src/app/sessions

volumes:
  wwebjs_sessions:
