version: '3.8'

services:
  app:
    container_name: wwebjs_api
    image: avoylenko/wwebjs-api:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE
    volumes:
      - wwebjs_sessions:/usr/src/app/sessions

volumes:
  wwebjs_sessions:
