version: '3.8'

services:
  wwebjsx:
    image: avoylenko/wwebjs-api:latest # Pull the image from Docker Hub
    restart: always
    container_name: wwebjsx
    ports:
      - "3000"
    env_file:
      - .env
    environment:
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL}
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE
      - MAX_ATTACHMENT_SIZE=5000000
      # - SET_MESSAGES_AS_SEEN=FALSE
      # - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE
      - CHROME_BIN=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
      # - NODE_ENV=production
    volumes:
      - wwebjsx:/usr/src/app/sessions

volumes:
  wwebjsx:
